### ISSUE TITLE
Wrong page shown in paginations after error occured while changing pages

### ISSUE THREAD

**Issue by Sabr1n4W** [THM-Health/PILOS#1291]
**Describe the bug**
The paginations show an incorrect page after the data has been reloaded without error after an error has occurred when changing pages.
The data is reloaded for the previous active page (page before the page change) but the active page shown is the new active page (page after the page change).

**To Reproduce**
1. Make sure an error occurs when switching to another page
2. Now reload the data through the reload button (data will be reloaded for the previous active page)
3. After that the pagination shows the new active page as active page and not the previous with which the data was reloaded.

E.g. An error occured when switching from the first page to the second page of the pagination. Now reload the data through the reload button (data is reloaded for first page). After that the pagination still shows the second page as the active page.

**Expected behavior**
1. Option (set pagination page to previous page)
Reset the active page within the pagination to the page with which the data was reloaded. 

2. Option (reload data with new active page)
Reload the data with the page that will be shown as active page. 

**Additional context**
This has not been tested for all paginations yet.

Currently this behaviour was found in:
- Room list (RoomsIndex)
- Room member list

**Comment by SamuelWei** [comment]
- The `usePaginator` class maintains a `first` value that is always set after a successful request.
- When the `first` value in `usePaginator` changes, it updates the `first` index in the PrimeVue paginator, resulting in a corresponding page change.

- After a successful request, the `first` index in `usePaginator` is set correctly.
- If a user attempts to change the page and the request fails, the `first` index in the PrimeVue paginator is still updated, but the `first` index in `usePaginator` remains unchanged.
- On the next successful request, the old page is reloaded, and the `usePaginator` values are updated. However, since the `usePaginator` values were not updated during the failed request, no change is propagated back to the PrimeVue paginator.
- As a result, the PrimeVue paginator displays an incorrect page number.
