### ISSUE TITLE
Can not promote users to moderators

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#560]
**Describe the bug**
After joining a meeting, normal users can not be promoted to moderators.

**To Reproduce**
1. Open a meeting with external (?) users
2. try to promote them to moderator
3. does not work

**Expected behavior**
When clicking on a user, I expected to see the "promote to moderator" option and be able to promote the user.

**Additional context**
This works in greenlight also for unauthenticated users.

**Comment by SamuelWei** [comment]
External users join a meeting with the guest parameter, this is important for the correct behaivoir of the lobby.

The BBB team made the design dessision that guest users can never be promoted to moderators due to security reasons.

However to compensate this you cqn create individual room links for guest users that should be moderators.

**Comment by SamuelWei** [comment]
@tibroc: See my comment https://github.com/bigbluebutton/bigbluebutton/issues/16425#issuecomment-1427587008

**Comment by tibroc** [comment]
I now better understand the conceptual and technical problems behind this issue, however, a small review at the UOS revealed that this is still a usability deal breaker for us — mainly because people are very much used to a different behavior and already heavily rely on it.

Since a sustainable solution probably needs a refactoring of this part of the BBB API itself, this is likely not solved quickly. But maybe it is possible to implement a server-wide override in PILOS that does neither break existing PILOS installations, nor alienates veteran Greenlight users?
